sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- '6'
matrix:
  fast_finish: true
install:
- curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
before_script:
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test:ci
- echo $TRAVIS_BRANCH
- if [ $TRAVIS_BRANCH = 'develop' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/warranties/
  --base-href /pages/warranty-stage/; fi
- if [ $TRAVIS_BRANCH = 'master' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/warranties/
  --base-href /pages/warranty-1/; fi

deploy:
- provider: script
  skip_cleanup: true
  script: "theme -e production upload"
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: "theme -e --force stage upload"
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: "theme -e --force development upload"
  on:
    branch: develop