sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- stable
matrix:
  fast_finish: true
install:
- curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
script:
- echo Ya!

deploy:
- provider: script
  skip_cleanup: true
  script: theme -e production upload
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: theme -p $STAGE_PASSWORD -s $STAGE_SHOP -t $STAGE_THEME_ID --force
  on:
    branch: stage
