sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- stable
matrix:
  fast_finish: true
notifications:
webhooks: https://outlook.office.com/webhook/3b6879b1-8830-4f1e-a4bf-e4e9761460c1@07261bf4-4bea-401b-ac9c-de322838b380/TravisCI/1f67dcfbd53a462b8a80b84ae90fd358/f4d49b17-6166-458f-81cd-2b5acbc3801c
install:
- curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
script:
- echo Ya!

deploy:
- provider: script
  skip_cleanup: true
  script: theme upload -p $PROD_PASSWORD -s $PROD_SHOP -t $PROD_THEME_ID --force --no-update-notifier --ignores './themekit_ignores'
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: theme upload -p $STAGE_PASSWORD -s $STAGE_SHOP -t $STAGE_THEME_ID --force --no-update-notifier --ignores './themekit_ignores'
  on:
    branch: stage
