sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- stable
matrix:
  fast_finish: true
install:
- curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
script:
- echo Ya!

deploy:
- provider: script
  skip_cleanup: true
  script: theme upload -p $PROD_PASSWORD -s $PROD_SHOP -t $PROD_THEME_ID --force --no-update-notifier --ignores './themekit_ignores'
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: theme upload -p $STAGE_PASSWORD -s $STAGE_SHOP -t $STAGE_THEME_ID --force --no-update-notifier --ignores './themekit_ignores'
  on:
    branch: stage
